name: greens_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18+2
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^23.1.44
  flutter_barcode_scanner: ^2.0.0
  uuid: ^4.5.1
  intl: ^0.18.1  # Updated from ^0.17.0 to resolve conflict with syncfusion_flutter_charts
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.65.0  # Mise à jour vers la dernière version
  image_picker: ^1.0.5
  location: ^5.0.3  # Replace geolocator with location package
  url_launcher: ^6.2.2
  path_provider: ^2.1.5
  permission_handler: ^11.1.0
  # Http pour les requêtes API
  http: ^0.13.5
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.1
  langchain: ^0.7.7+2
  sqflite: ^2.4.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  # Pour le parcours écologique et les défis
  timeline_tile: ^2.0.0
  confetti: ^0.7.0

# Dependency overrides pour résoudre les conflits
dependency_overrides:
  fl_chart: ^0.65.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/products/
    - assets/images/profile/
