/// Classe de constantes pour les routes de l'application
class AppRoutes {
  static const String splash = '/splash';
  static const String splashConnect = '/splashConnect';
  static const String login = '/login';
  static const String signup = '/signup';
  static const String forgotPassword = '/forgot-password';
  static const String onboarding = '/onboarding';
  static const String home = '/home';
  static const String profile = '/profile';
  static const String settings = '/settings';
  static const String setting = '/setting'; // Alias pour compatibilité
  static const String carbon = '/carbon';
  static const String carbonDashboard = '/carbonDashboard';
  static const String carbonCalculator = '/carbonCalculator';
  static const String carbonResults = '/carbon-results';
  static const String rewards = '/rewards';
  static const String productScan = '/product-scan';
  static const String productScanner = '/productScanner'; // Alias pour compatibilité
  static const String scanner = '/scanner'; // Alias pour compatibilité
  static const String productDetails = '/product-details';
  static const String productComparison = '/product-comparison';
  static const String products = '/products';
  static const String community = '/community';
  static const String communityChallenge = '/community-challenge';
  static const String communityImpact = '/communityImpact';
  static const String ecoTips = '/eco-tips';
  static const String goals = '/goals';
  static const String chatbot = '/chatbot';
  static const String ecoChatbot = '/ecoChatbot';
  static const String question1 = '/question1';
  static const String question2 = '/question2';
  static const String question3 = '/question3';
  static const String question4 = '/question4';
  static const String question5 = '/question5';
  static const String actionHub = '/actionHub';
  static const String socialHub = '/socialHub';
  static const String personalDashboard = '/personal-dashboard';
  static const String dashboard = '/dashboard'; // Alias pour compatibilité
  static const String userDashboard = '/userDashboard'; // Alias pour compatibilité
  static const String quickImpact = '/quickImpact';
  static const String quickImpactActions = '/quickImpactActions';
  static const String badges = '/badges';
  static const String article = '/article';
  static const String articles = '/articles';
  static const String blog = '/blog';
  static const String help = '/help';
  static const String legaleNotice = '/legaleNotice';
  static const String methodology = '/methodology';
  static const String localCommunity = '/localCommunity';
} 